// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZs7ZtPLFrWIa3iM5neXfr71-t71qaA1w',
    appId: '1:924032639569:web:1155e7714b654ce5d6ce70',
    messagingSenderId: '924032639569',
    projectId: 'nasys-6609',
    authDomain: 'nasys-6609.firebaseapp.com',
    databaseURL: 'https://nasys-6609-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nasys-6609.appspot.com',
    measurementId: 'G-NPHP5F674M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDObylKkNrfWKle90UggloJTfQ6SffAV20',
    appId: '1:924032639569:android:2320770a677a762cd6ce70',
    messagingSenderId: '924032639569',
    projectId: 'nasys-6609',
    databaseURL: 'https://nasys-6609-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nasys-6609.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOz2UqB8kyPqDNmzKOacdbdQ2ipzruYRI',
    appId: '1:924032639569:ios:952bc25783db75c9d6ce70',
    messagingSenderId: '924032639569',
    projectId: 'nasys-6609',
    databaseURL: 'https://nasys-6609-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nasys-6609.appspot.com',
    iosClientId: '924032639569-mbust3j969usrtvv918enc6t3vf1cmbs.apps.googleusercontent.com',
    iosBundleId: 'digital.minh.nasys',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOz2UqB8kyPqDNmzKOacdbdQ2ipzruYRI',
    appId: '1:924032639569:ios:952bc25783db75c9d6ce70',
    messagingSenderId: '924032639569',
    projectId: 'nasys-6609',
    databaseURL: 'https://nasys-6609-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nasys-6609.appspot.com',
    iosClientId: '924032639569-mbust3j969usrtvv918enc6t3vf1cmbs.apps.googleusercontent.com',
    iosBundleId: 'digital.minh.nasys',
  );
}
